### ISSUE TITLE
state change ignored - not writable

### ISSUE THREAD

**Issue by stijnsimons** [Apollon77/ioBroker.daikin-cloud#139]
Hello,

From time to time i'm getting this error when passing MQTT messages onto the daiking cloud API.
Any idea what might be causing this? After enabling and disabling the MQTT subscription for this particular parameter, the problem is usually solved.

![image](https://user-images.githubusercontent.com/93920739/192724079-76d86dc8-3d9b-42fe-a451-75c5f045e658.png)

Thanks

**Comment by Apollon77** [comment]
Yes then the devices are offline for the cloud ... when this happens the data getting from cloud flag all values as read only ...

**Comment by Apollon77** [comment]
Only idea would be that the adapter do not change the objects (so if a state was writebale we do not revert that to read-only" but then you send out stuff to the cloud and no idea what will happen

**Comment by stijnsimons** [comment]
Thanks for the fast reply.
Would it help to flag the "ACK" settings? i guess not, because the mqtt message is send correctly, it's the publish to the Daikin cloud that doesn't work in the case a device is offline (even briefly at the moment of sending the data).

Or am i missing something?

Thanks!

**Comment by Apollon77** [comment]
enabling that "ack" will mean that you only update values but never control them.

In fact the issue happens because of the objects being read only ... so in fact when the device is offline you Can not control it. So it is a "semantic" issue. The "warn" log happens because you try to write a value into an object which is "right now" not writable. So mqtt-client forwards the state value that you control from somewhere else correctly, but this is not allowed because device is offline. So also daikin-cloud ignores this.

You can not do anything really ... beside making sure to only write values to online devices.

As said I could try to "leave" it writeable even if offline, but then the write request is also declined in the end by the cloud because device offfline (but you would maybe not see any log or such)

**Comment by stijnsimons** [comment]
Wouldn't it be possible to verify if the data was written correctly, and if not, retry a configurable amount of times?
Devices being offline for a very short period of time is quite common with Daikin cloud devices I'm afraid. Happens quite regularly.
